project: example-project
pipeline: example-pipeline
verbose: false
writers:
- data_collection_consent: true
  formats: ['protobuf']
  output_path: whylabs
  type: whylabs
- formats:
  - protobuf
  output_path: output
  path_template: $name/dataset_summary
  filename_template: dataset_summary_$datetime_timestamp
  type: local