[tool.poetry]
name = "whylogs"
version = "1.0.0"
description = "Profile and monitor your ML data pipeline end-to-end"
authors = ["WhyLabs.ai <support@whylabs.ai>"]
license = "Apache-2.0"
homepage = "https://docs.whylabs.ai"
readme = "README.md"
include = ["whylogs/core/proto/v0/*.py*", "whylogs/core/proto/*.py*"]


[tool.poetry.dependencies]
python = ">=3.7.1, <4.0"
whylogs-sketching = "3.4.0.dev9"
protobuf = ">=3.15.5"
importlib-metadata = { version = ">=0.23", python = "<3.8" }
typing-extensions = ">=typing-extensions"
pybars3 = { version = "^0.9", optional = true }
ipython = { version = "*", optional = true }
scipy = {version = "<1.8", extras = ["viz"]}

[tool.poetry.dev-dependencies]
2to3 = "^1.0"
black = { version = "*", allow-prereleases = true }
flake8 = "*"
flake8-docstrings = { version = "^1.6.0", optional = true }
isort = "^5.6"
mkdocs-material = "^8"
mypy = ">=0.942,<1"
pre-commit = "^2.8"
pytest = "^6.2"
pytest-cov = "^3"
pytest-mock = "^3.3"
autoflake = "^1.4"
mypy-protobuf = ">=3.2.0"
types-protobuf = ">=0.1.14"
pandas = "*"
pandas-stubs = "*"
ipykernel = ">=6.11" # for developing in Jupyter notebook
sphinx = "*"
sphinx-autoapi = "*"
autodoc-pydantic = "^1.6.1"
sphinx-copybutton = "^0.5.0"
numpydoc = "*"
furo = "^2022.3.4"
sphinx-autodoc-typehints = "^1.17.0"
types-python-dateutil = "^2.8.12"


[tool.poetry.extras]
docs = [
    "sphinx",
    "sphinx-autoapi",
    "ipython",
    "nbsphinx",
    "numpydoc",
    "furo",
    "sphinx-autodoc-typehints",
]
viz = [
    "ipython",
    "pybars3",
]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
src_paths = ["whylogs", "tests"]
skip = ["whylogs/core/proto/", ".venv", "docs"]
multi_line_output = 3


[tool.mypy]
disallow_incomplete_defs = true
disallow_untyped_defs = true
explicit_package_bases = true
files = ["whylogs/**/*.py"]
namespace_packages = true
show_error_codes = true
plugins = [
    "numpy.typing.mypy_plugin"
]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | tests
    | whylogs/core/proto
    | whylogs/viz/html
    | docs
    | *.pyi
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.pytest.ini_options]
addopts = "-q"
minversion = "6.0"
testpaths = ["tests"]

[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | tests
    | whylogs/core/proto
    | docs
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
