[tool.isort]
profile = "black"
src_paths = ["whylogs_v1", "tests"]
skip = ["whylogs_v1/core/proto/", ".venv"]
multi_line_output = 3


[tool.mypy]
disallow_incomplete_defs = true
disallow_untyped_defs = true
explicit_package_bases = true
files = ["whylogs_v1/**/*.py"]
namespace_packages = true
show_error_codes = true
plugins = [
    "numpy.typing.mypy_plugin"
]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | tests
    | whylogs_v1/core/proto
    | *.pyi
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''


[tool.poetry]
name = "whylogs_v1"
version = "1.0.0"
description = "Profile and monitor your ML data pipeline end-to-end"
authors = ["WhyLabs.ai <support@whylabs.ai>"]
license = "Apache-2.0"
homepage = "https://docs.whylabs.ai"
readme = "README.md"
include = ["whylogs_v1/py.typed"]

[tool.poetry.dependencies]
python = ">=3.7.1, <4.0"
whylogs-datasketches = "3.4.0.dev3"
protobuf = ">=3.15.5"
importlib-metadata = { version = ">=0.23", python = "<3.8" }

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
flake8 = "*"
isort = "^5.6"
mkdocs-material = "^8"
mypy = ">=0.910,<1"
pre-commit = "^2.8"
pytest = "^6.2"
pytest-cov = "^3"
pytest-mock = "^3.3"
autoflake = "^1.4"
mypy-protobuf = ">=3.2.0"
types-protobuf = ">=0.1.14"
pandas = ">=1.3"
pandas-stubs = ">=1.2"
ipykernel = ">=6.11" # for developing in Jupyter notebook


[tool.pytest.ini_options]
addopts = "-q"
minversion = "6.0"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | tests
    | whylogs_v1/core/proto
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
